"""Domain Compiler — auto-compile Clinical Practice Guidelines into Decision Graphs.

Input: CPG text (PDF/Markdown/plain text)
Output: DecisionGraph (nested decision tree + priority paths + branch conditions)

Algorithm:
1. Expand structured lists ("any of the following:") into individual if-then rules
2. Segment sentences (jieba Chinese / regex English)
3. Parse each sentence for triggers, conditions, actions, negation, nesting depth
4. Build recursive decision tree with parent-child branching
5. Extract root-to-leaf priority paths
6. Compile DecisionGraph with full metadata

Core scientific contribution: knowledge engineer replaced by compiler.
Based on: ACT-R Production Compilation (Taatgen & Lee 2003)
"""
from __future__ import annotations
import re
import os
import json
import uuid
import logging
from typing import List, Dict, Optional, Tuple, Set
from datetime import datetime, timezone
from schemas.decision_graph import DecisionGraph, DecisionNode, PriorityPath

logger = logging.getLogger(__name__)

try:
    import spacy
    NLP = spacy.load("zh_core_web_sm")
    HAS_SPACY = True
except (ImportError, OSError):
    NLP = None
    HAS_SPACY = False

try:
    import jieba
    HAS_JIEBA = True
except ImportError:
    HAS_JIEBA = False

# ── Regex patterns ──

# Nesting depth keywords
NESTING_KEYWORDS = [
    (1, ['首先', '第一步', '初始', 'first', 'initially']),
    (2, ['然后', '其次', '接着', '第二步', 'then', 'next', 'subsequently']),
    (3, ['最后', '第三步', 'finally', 'lastly']),
]

# Sentence boundaries
SENTENCE_BOUNDARY = re.compile(r'[。.！!？?\n;；]+')

# English CPG: "If X, recommend/request/perform Y"
EN_IF_THEN_RE = re.compile(
    r'(?:if|when|whenever)\s+(.+?)'
    r'[，,]\s*(?:then\s+)?'
    r'((?:recommend|request|perform|obtain|order|consider|patient|rule)\s+'
    r'(?:an?\s+)?'
    r'(?:ankle|foot|knee|shoulder|wrist|hip|spine|cervical|head|chest|imaging|patient|rule)?\s*'
    r'.+?(?:X-ray|radiograph|CT|MRI|imaging|scan|assessment|evaluation|cleared|required|needed|indicated|address|include|document|specify|describe|present|provide|identify|determine|establish|ensure|plan|implement|monitor|conduct|review|take|continually|communicate|evaluate|select|control))',
    re.IGNORECASE,
)

# Expanded list pattern: "If Title identifies... then A systematic review must include"
# This is generated by _expand_structured_lists for non-clinical domains
EN_EXPANDED_IF_THEN_RE = re.compile(
    r'(?:if|when|whenever)\s+(.+?)'
    r'[，,]\s*then\s+'
    r'(.+)$',
    re.IGNORECASE,
)

# English CPG: "Inability to X, recommend Y"
EN_ACTION_RE = re.compile(
    r'(recommend|request|obtain|perform|order|consider|suggest)'
    r'\s+(?:an?\s+)?(.+)$',
    re.IGNORECASE,
)

# Chinese CPG pattern: "X的患者建议Y" (patients with X should Y)
CN_CPG_RE = re.compile(
    r'(.+?)(?:的患者|的伤者|的病人|的个体|情况下|的时候|时)'
    r'(.*?)'
    r'(?:建议|应当|应该|需要|必须|推荐|进行|拍|做|查|考虑|给予|评估|不推荐|不建议)'
    r'(.*)',
    re.IGNORECASE,
)

# Chinese if-then pattern: "如果X，建议Y" (if X, then recommend Y)
CN_IF_THEN_RE = re.compile(
    r'(?:如果|若|假如|当|一旦|倘若)'
    r'\s*(.+?)'
    r'[，,]\s*(?:则|那么|就)?'
    r'(?:建议|应当|应该|必须|推荐|需要|进行|拍|做|查|考虑|给予|评估|保守|不推荐|不建议|不需)'
    r'\s*(.*)',
    re.IGNORECASE,
)

# Negation patterns
NEGATION_RE = re.compile(
    r'(?:不建议|不推荐|不需要|无需|不必|不用|没必要|不应该|不满足|不适用|none|'
    r'is not indicated|no.*?needed|unnecessary|contraindicated)',
    re.IGNORECASE,
)


# ── Failure Registry ──

from pathlib import Path as _Path

_DEFAULT_REGISTRY = str(_Path(__file__).resolve().parent.parent.parent / "data" / "compiler_failure_registry.json")
FAILURE_REGISTRY_PATH = os.environ.get("MINTA_FAILURE_REGISTRY_PATH", _DEFAULT_REGISTRY)


def _load_failure_registry() -> dict:
    if os.path.exists(FAILURE_REGISTRY_PATH):
        with open(FAILURE_REGISTRY_PATH, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {}


def _save_failure_registry(registry: dict):
    os.makedirs(os.path.dirname(FAILURE_REGISTRY_PATH), exist_ok=True)
    with open(FAILURE_REGISTRY_PATH, 'w', encoding='utf-8') as f:
        json.dump(registry, f, indent=2, ensure_ascii=False)


class DomainCompiler:
    """Compile CPG text into executable DecisionGraph.

    Supports fallback chain: when primary strategy yields too few rules,
    automatically tries alternative parsing strategies. Known failure
    patterns are cached in a registry for strategy pre-selection.
    """

    def __init__(self):
        self._node_counter = 0
        self._failure_registry = _load_failure_registry()
        self._last_strategy = None

    def compile(self, cpg_text: str, domain: str, source: str = "",
                min_expected_rules: int = 3) -> DecisionGraph:
        """Compile CPG text with automatic fallback.

        Strategies (tried in order):
          1. full: sequential + structured + parse
          2. sequential_only: sequential + parse (skip structured)
          3. structured_only: structured + parse (skip sequential)
          4. raw: parse only (no expansion)

        If a known failure pattern matches, the successful strategy from
        the registry is tried first.
        """
        text_hash = str(hash(cpg_text))
        registry_key = f"{domain}:{text_hash}"

        # Check if we've seen this pattern before
        known = self._failure_registry.get(registry_key)
        if known and known.get('winning_strategy'):
            strategies = [known['winning_strategy'], 'full', 'sequential_only',
                          'structured_only', 'raw']
        else:
            strategies = ['full', 'sequential_only', 'structured_only', 'raw']

        best_graph = None
        best_rules = 0
        tried = []

        for strategy in strategies:
            # Deduplicate
            if strategy in tried:
                continue
            tried.append(strategy)

            graph = self._compile_with_strategy(cpg_text, domain, source, strategy)
            n_rules = len(graph.rules)

            if n_rules >= min_expected_rules:
                # Success — cache the winning strategy
                self._failure_registry[registry_key] = {
                    'domain': domain,
                    'source': source[:100],
                    'tried': tried,
                    'winning_strategy': strategy,
                    'n_rules': n_rules,
                    'timestamp': datetime.now(timezone.utc).isoformat(),
                }
                _save_failure_registry(self._failure_registry)
                self._last_strategy = strategy
                return graph

            if n_rules > best_rules:
                best_rules = n_rules
                best_graph = graph

        # No strategy hit the threshold — return best attempt
        self._failure_registry[registry_key] = {
            'domain': domain,
            'source': source[:100],
            'tried': tried,
            'winning_strategy': None,
            'best_n_rules': best_rules,
            'timestamp': datetime.now(timezone.utc).isoformat(),
        }
        _save_failure_registry(self._failure_registry)
        self._last_strategy = 'best_available'
        logger.warning(
            f"Compiler fallback exhausted for {domain}: best={best_rules} rules "
            f"(needed {min_expected_rules}). Strategies tried: {tried}"
        )
        return best_graph or self._compile_with_strategy(cpg_text, domain, source, 'raw')

    def _compile_with_strategy(self, cpg_text: str, domain: str, source: str,
                                strategy: str) -> DecisionGraph:
        """Run compilation with a specific expansion strategy."""
        self._node_counter = 0

        if strategy == 'raw':
            expanded_text = cpg_text
        elif strategy == 'sequential_only':
            expanded_text = self._expand_sequential_steps(cpg_text)
        elif strategy == 'structured_only':
            expanded_text = self._expand_structured_lists(cpg_text)
        else:  # 'full'
            expanded_text = self._expand_sequential_steps(cpg_text)
            expanded_text = self._expand_structured_lists(expanded_text)

        parsed = self._parse_all(expanded_text)
        root, registry = self._build_tree(parsed)

        nodes = []
        self._flatten(root, nodes, registry)
        priority_paths = self._extract_paths(root, registry)

        return DecisionGraph(
            domain=domain,
            source=source or "CPG compilation",
            source_type="cpg",
            nodes=nodes,
            priority_paths=priority_paths,
            entry_node_id=root.id if root else None,
            metadata={
                "raw_text_length": len(cpg_text),
                "expanded_text_length": len(expanded_text),
                "parsed_clauses": len(parsed),
                "triggers_found": len(set(t for p in parsed for t in p.get("triggers", []))),
                "parser": "spacy" if HAS_SPACY else ("jieba" if HAS_JIEBA else "regex"),
                "compile_strategy": strategy,
            },
            compiled_at=datetime.now(timezone.utc),
        )

    # ── Sequential Step Expansion ──

    def _expand_sequential_steps(self, text: str) -> str:
        """Expand 'Step N — Name (logic):' structures into individual if-then rules.

        Handles sequential CPG formats like the Canadian C-Spine Rules:
          Step 1 — High Risk Factors (any YES → imaging required):
          (A) item1
          (B) item2
          Step 2 — Low Risk Factors (...):
          (A) item3

        Each item becomes an if-then rule with the step's action.
        Steps are separated by the next 'Step N' header or end of text.
        """
        if not text or not isinstance(text, str):
            return text or ""

        text = text.replace('\r\n', '\n').replace('\r', '\n')

        # Find all step headers: "Step N — Name (logic):"
        step_pattern = re.compile(
            r'^Step\s+(\d+)\s*[-—–]\s*(.+?)\s*\((.+?)\)\s*[:：]\s*$',
            re.MULTILINE | re.IGNORECASE,
        )
        step_matches = list(step_pattern.finditer(text))
        if not step_matches:
            return text

        all_rules = []
        # Keep preamble (text before first step)
        first_step_start = step_matches[0].start()
        preamble = text[:first_step_start].strip()
        if preamble:
            all_rules.append(preamble)

        for idx, sm in enumerate(step_matches):
            step_num = sm.group(1)
            step_name = sm.group(2).strip()
            step_logic = sm.group(3).strip()

            # Determine action from step logic
            action = self._infer_step_action(step_logic, step_name)

            # Extract items: text from end of this header to start of next step (or EOF)
            items_start = sm.end()
            items_end = step_matches[idx + 1].start() if idx + 1 < len(step_matches) else len(text)
            items_block = text[items_start:items_end].strip()

            items = self._parse_step_items(items_block)
            if items:
                for item in items:
                    if re.match(r'^if\s+', item, re.IGNORECASE):
                        # Already a full if-then rule; action is already embedded
                        all_rules.append(f"{item}.")
                    else:
                        all_rules.append(f"If {item}, then {action}.")
                logger.info(
                    f"Expanded Step {step_num} ({step_name}): "
                    f"{len(items)} items -> action '{action}'"
                )

        return '\n'.join(all_rules)

    def _infer_step_action(self, logic: str, step_name: str) -> str:
        """Infer the recommended action for INDIVIDUAL items within a step.

        Key semantic distinction: Step 2's logic '(if NO to all -> imaging required)'
        means imaging only triggers when ALL items are absent. Each individual item
        being present -> proceed to neck rotation. So item-level action is 'proceed',
        not 'imaging'.

        Step 1: any single high-risk factor present -> imaging (item-level action = imaging)
        Step 2: any single low-risk factor present -> proceed (item-level action = proceed)
        Step 3: unable to rotate -> imaging; able -> cleared
        """
        name_lower = step_name.lower()
        logic_lower = logic.lower()

        # Step 1 — High Risk: each item directly triggers imaging
        if 'high risk' in name_lower:
            return 'perform cervical spine imaging'

        # Step 2 — Low Risk: each item allows proceeding to ROM check
        # (imaging only triggers if ALL items absent — a meta-rule, not per-item)
        if 'low risk' in name_lower:
            return 'perform neck rotation assessment'

        # Step 3 — Rotation: check logic direction
        if 'rotation' in name_lower or 'neck' in name_lower:
            if re.search(r'unable|cannot|impaired|limited|restricted', logic_lower):
                return 'perform cervical spine imaging'
            if re.search(r'able|can|normal|full|cleared', logic_lower):
                return 'no imaging needed, rule cleared'
            return 'perform cervical spine imaging'

        # Generic fallback
        if re.search(r'imaging', logic_lower):
            return 'perform cervical spine imaging'
        if re.search(r'cleared|discharge|safe', logic_lower):
            return 'no imaging needed, rule cleared'
        if re.search(r'rotation|proceed|assess', logic_lower):
            return 'perform neck rotation assessment'

        return 'perform further assessment'

    def _parse_step_items(self, items_block: str) -> list:
        """Parse bullet/number items from a step's items block.

        Handles lettered items (A), (B), prose with '->' rules, and plain text.
        Items that start with 'If' or contain '->' are passed through as-is
        (already fully formed rules), avoiding double-wrapping.
        """
        items = []
        for line in items_block.split('\n'):
            s = line.strip()
            if not s:
                continue

            # Prose paragraphs that aren't list items
            is_prose = bool(re.search(
                r'^(?:patient|the\s+patient|note|exclusion|contraindication)',
                s, re.IGNORECASE))

            # Already-formed if-then rules (with -> or Unicode arrow)
            if '->' in s or '→' in s:
                # Normalize "If X -> Y" / "If X → Y" to "If X, then Y"
                s = re.sub(r'\s*[-–—]+>\s*|→', ', then ', s)
                s = s.rstrip('.')
                # Normalize action verbs so EN_IF_THEN_RE can match
                s = re.sub(r', then\s+imaging required', ', then perform cervical spine imaging', s, flags=re.IGNORECASE)
                s = re.sub(r', then\s+imaging indicated', ', then perform cervical spine imaging', s, flags=re.IGNORECASE)
                s = re.sub(r', then\s+no imaging needed,\s*rule cleared', ', then patient cleared, no imaging required', s, flags=re.IGNORECASE)
                s = re.sub(r', then\s+no imaging needed', ', then patient cleared, no imaging required', s, flags=re.IGNORECASE)
                s = re.sub(r', then\s+rule cleared', ', then patient cleared, no imaging required', s, flags=re.IGNORECASE)
                items.append(s)
                continue

            if is_prose and not s.startswith('If'):
                continue  # skip descriptive prose

            # Remove bullet prefix: (A), 1., -, etc.
            s = re.sub(
                r'^[\(（]?[A-Ea-e\d][\)）\.\、]?\s*|^[\d]+[\.\)\、]?\s*|^[\-\*\•\►]\s*',
                '', s,
            ).strip().rstrip('.,;，。；')
            if s and len(s) > 8:
                items.append(s)
        return items

    # ── Structured List Expansion ──

    def _expand_structured_lists(self, text: str) -> str:
        """Expand CPG 'any of the following:' lists into individual if-then rules.

        Handles formats like:
        - 'Request an X-ray for [condition] if they have any of: (A) X, (B) Y'
        - '满足以下任一条件时需要X检查：1. 条件A  2. 条件B'
        """
        if not text or not isinstance(text, str):
            return text or ""

        # Normalize line endings
        text = text.replace('\r\n', '\n').replace('\r', '\n')

        # Split text into blocks
        blocks = re.split(r'\n\n+', text)

        # Merge: if a block ends with "following:" and next block has list items
        merged = []
        skip_next = False
        for i, block in enumerate(blocks):
            if skip_next:
                skip_next = False
                continue
            # If this block looks like a list header and next block has items
            is_header = bool(re.search(
                r'(?:any|all|either|任一|任意|下列|以下)\s+(?:one\s+)?(?:of\s+)?(?:the\s+)?following'
                r'(?:\s+criteria|\s+conditions|\s+findings)?\s*[:：]\s*$',
                block.strip(), re.IGNORECASE,
            ))
            if is_header and i + 1 < len(blocks):
                # Merge with next block
                merged.append(block + '\n' + blocks[i + 1])
                skip_next = True
            else:
                merged.append(block)

        result_blocks = []

        for block in merged:
            if not block.strip():
                result_blocks.append(block)
                continue

            # Find ALL "any of the following:" sections within this block.
            # Multi-section CPGs (e.g. Ottawa Ankle = ankle series + foot series)
            # appear as a single block when no blank line separates them.
            section_pattern = re.compile(
                r'(.+?(?:any|all|either|任一|任意|下列|以下)\s+'
                r'(?:one\s+)?(?:of\s+)?(?:the\s+)?following'
                r'(?:\s+criteria|\s+conditions|\s+findings)?\s*[:：])',
                re.IGNORECASE,
            )

            # Find all header positions
            all_headers = list(section_pattern.finditer(block))
            if not all_headers:
                result_blocks.append(block)
                continue

            all_rules = []
            for idx, hm in enumerate(all_headers):
                header = hm.group(0)
                header_end = hm.end()
                action = self._extract_cpg_action(header)

                # Tail: from header end to the start of the next header (or end of block)
                next_start = all_headers[idx + 1].start() if idx + 1 < len(all_headers) else len(block)
                tail = block[header_end:next_start].strip()

                item_lines = tail.split('\n')
                items = []
                criterion_keywords = ('inability', 'ability', 'pain', 'tenderness', 'swelling',
                                      'fever', 'numbness', 'tingling', 'weakness', 'deformity',
                                      'cannot', 'unable', 'limited', 'restricted', 'positive',
                                      'negative', 'absent', 'present')
                for line in item_lines:
                    s = line.strip()
                    if not s:
                        continue
                    has_prefix = bool(re.match(
                        r'^[\(（]?[A-Za-z0-9]{1,2}[\)）\.\、]\s*'
                        r'|^[\d]+[\.\)\、]\s*'
                        r'|^[\-\*\•\►]\s*',
                        s,
                    ))
                    is_criterion = any(kw in s.lower() for kw in criterion_keywords)
                    # Keep: lettered items, or short criterion-looking continuation lines
                    if not has_prefix and not is_criterion:
                        continue
                    s_raw = s
                    s = re.sub(
                        r'^[\(（]?[A-Za-e\d][\)）\.\、]?\s*'
                        r'|^[\(（]?[A-Za-z]{2}\d?[\)）\.\、]\s*'
                        r'|^[\d]+[\.\)\、]?\s*'
                        r'|^[\-\*\•\►]\s*',
                        '', s,
                    ).strip().rstrip('.,;，。；')
                    if s and len(s) > 8:
                        items.append(s)

                if items:
                    for item in items:
                        all_rules.append(f"If {item}, then {action}.")
                    logger.info(f"Expanded {len(items)} items from section {idx+1}: {header[:60]}...")

            if all_rules:
                result_blocks.append('\n'.join(all_rules))
                continue

            result_blocks.append(block)

        return '\n\n'.join(result_blocks)

    def _extract_cpg_action(self, header: str) -> str:
        """Extract the recommended action from a CPG header sentence.

        'Request an x-ray for a patient with traumatic ankle pain...'
        -> 'request ankle x-ray'
        """
        # English: "Request/Recommend/Perform [an] x-ray/CT/MRI"
        m = re.search(
            r'(request|recommend|perform|obtain|order|consider)\s+'
            r'(?:an?\s+)?'
            r'((?:ankle|foot|knee|shoulder|wrist|hip|spine|head|chest|'
            r'踝|足|膝|肩|腕|髋|脊柱|颈|头|胸)?\s*'
            r'(?:[xX]-ray|X-ray|xray|radiograph|radiographic series|CT|MRI|imaging|scan|'
            r'X光|CT|磁共振|影像|检查|扫描|射线))',
            header, re.IGNORECASE,
        )
        if m:
            verb = m.group(1)
            rest = m.group(2).strip()

            # If anatomical site wasn't directly in the action phrase, try to
            # find it in the header (e.g. "ankle pain" -> "ankle", "midfoot" -> "foot")
            if not re.search(r'(?:ankle|foot|knee|shoulder|wrist|hip|spine|head|chest)',
                             rest, re.IGNORECASE):
                site_map = {
                    'ankle': 'ankle', 'foot': 'foot', 'midfoot': 'foot',
                    'knee': 'knee', 'shoulder': 'shoulder', 'wrist': 'wrist',
                    'hip': 'hip', 'spine': 'spine', 'cervical': 'c-spine',
                    'head': 'head', 'chest': 'chest', 'neck': 'c-spine',
                }
                header_lower = header.lower()
                for site_word, site_label in site_map.items():
                    if site_word in header_lower:
                        rest = f"{site_label} {rest}"
                        break

            return f"{verb} {rest}".strip()

        # Chinese action verbs: "建议/需要/应当..." (recommend/need/should...)
        m = re.search(
            r'(建议|应当|应该|需要|必须|推荐|进行|拍|做|查)'
            r'\s*(.+)',
            header,
        )
        if m:
            return f"{m.group(1)}{m.group(2)}".strip()

        # Fallback: return cleaned header
        return header.strip().rstrip('.:：。，,')

    # ── Parsing ──

    def _parse_all(self, text: str) -> List[Dict]:
        """Parse all sentences into structured clauses."""
        if not text:
            return []

        sentences = self._segment(text)
        parsed = []
        for sent in sentences:
            clause = self._parse_sentence(sent)
            if clause:
                parsed.append(clause)
        return parsed

    def _segment(self, text: str) -> List[str]:
        if not text:
            return []
        raw = SENTENCE_BOUNDARY.split(text)
        return [s.strip() for s in raw if len(s.strip()) > 3]

    def _parse_sentence(self, sentence: str) -> Optional[Dict]:
        """Parse one sentence for clinical decision logic."""
        clause = {
            "text": sentence,
            "triggers": [],
            "actions": [],
            "conditions": [],
            "is_negative": False,
            "nesting_depth": 0,
            "references": [],
        }

        # Try English if-then (clinical: restricted vocabulary)
        en_match = EN_IF_THEN_RE.search(sentence)
        if en_match:
            clause["triggers"].append(en_match.group(1).strip())
            clause["actions"].append(en_match.group(2).strip())
            clause["nesting_depth"] = 1
            return self._finalize_clause(clause, sentence)

        # Try expanded if-then (non-clinical: any verb, from Normalizer output)
        en_exp = EN_EXPANDED_IF_THEN_RE.search(sentence)
        if en_exp:
            clause["triggers"].append(en_exp.group(1).strip())
            clause["actions"].append(en_exp.group(2).strip())
            clause["nesting_depth"] = 1
            return self._finalize_clause(clause, sentence)

        # Try Chinese CPG pattern "X的患者建议Y"
        cn_match = CN_CPG_RE.search(sentence)
        if cn_match:
            clause["triggers"].append(cn_match.group(1).strip())
            mid = cn_match.group(2).strip()
            if mid and len(mid) > 2:
                clause["nesting_depth"] = 1
            clause["actions"].append(cn_match.group(3).strip())
            return self._finalize_clause(clause, sentence)

        # Try Chinese if-then pattern "如果X，建议Y"
        cn_if = CN_IF_THEN_RE.search(sentence)
        if cn_if:
            clause["triggers"].append(cn_if.group(1).strip())
            clause["actions"].append(cn_if.group(2).strip())
            clause["nesting_depth"] = 1
            return self._finalize_clause(clause, sentence)

        # Try generic action pattern
        act_match = EN_ACTION_RE.search(sentence)
        if act_match:
            clause["actions"].append(f"{act_match.group(1)} {act_match.group(2)}".strip())
            clause["triggers"].append(sentence[:100])
            return self._finalize_clause(clause, sentence)

        # Nesting detection
        for depth, keywords in NESTING_KEYWORDS:
            for kw in keywords:
                if kw in sentence.lower():
                    clause["nesting_depth"] = max(clause["nesting_depth"], depth)

        # Detect negation
        if NEGATION_RE.search(sentence):
            clause["is_negative"] = True

        # Detect references [1], [2-4], etc.
        refs = re.findall(r'\[(\d+(?:[-,]\d+)*)\]', sentence)
        clause["references"] = refs

        return self._finalize_clause(clause, sentence)

    def _finalize_clause(self, clause: Dict, sentence: str) -> Optional[Dict]:
        clause["triggers"] = list(set(clause["triggers"]))
        clause["actions"] = list(set(clause["actions"]))

        # Negation check
        if not clause["is_negative"]:
            clause["is_negative"] = bool(NEGATION_RE.search(sentence))

        # Return if meaningful
        if clause["triggers"] and clause["actions"]:
            return clause
        if clause["is_negative"] and clause["actions"]:
            return clause
        return None

    # ── Tree Building ──

    def _build_tree(self, parsed: List[Dict]) -> Tuple[Optional[DecisionNode], Dict]:
        if not parsed:
            return None, {}

        registry = {}
        root = DecisionNode(id="root", trigger="评估开始", action="", condition="", priority=0)
        registry["root"] = root

        parent_stack = [root]

        for i, clause in enumerate(parsed):
            depth = clause.get("nesting_depth", 0)
            triggers = clause.get("triggers", [])
            actions = clause.get("actions", [])
            conditions = clause.get("conditions", [])

            trigger_text = "; ".join(triggers) if triggers else (
                "; ".join(conditions[:2]) if conditions else clause["text"][:80]
            )
            action_text = "; ".join(actions) if actions else ""
            if clause.get("is_negative") and action_text:
                action_text = f"不建议: {action_text}"

            node_id = f"n{i}"
            node = DecisionNode(
                id=node_id,
                trigger=trigger_text,
                condition="; ".join(conditions[:2]),
                action=action_text,
                priority=i + 1,
                parent_id=None,
                children=[],
                metadata={
                    "source_text": clause["text"][:200],
                    "nesting_depth": depth,
                },
            )
            registry[node_id] = node

            # Pop to current depth (remove deeper ancestors)
            while len(parent_stack) > depth + 1:
                parent_stack.pop()
            # Remove previous sibling at same depth — peers share the
            # same parent, they are not parent-child to each other.
            if len(parent_stack) == depth + 1:
                parent_stack.pop()

            parent = root if depth == 0 or len(parent_stack) <= depth else parent_stack[-1]
            node.parent_id = parent.id
            parent.children.append(node_id)

            if len(parent_stack) <= depth:
                parent_stack.append(node)
            else:
                parent_stack[depth] = node

        return root, registry

    def _flatten(self, node, result, registry):
        if node is None:
            return
        result.append(node)
        for child_id in node.children:
            child = registry.get(child_id)
            if child:
                self._flatten(child, result, registry)

    # ── Priority Paths ──

    def _extract_paths(self, root, registry):
        if root is None:
            return []
        paths = []
        self._dfs(root, [], paths, registry)
        return paths

    def _dfs(self, node, current_path, paths, registry):
        current_path = current_path + [node.id]
        if not node.children:
            paths.append(PriorityPath(
                node_ids=current_path,
                frequency=1,
                description=" → ".join(
                    registry[nid].trigger[:60] for nid in current_path if nid in registry
                ),
            ))
        else:
            for child_id in node.children:
                child = registry.get(child_id)
                if child:
                    self._dfs(child, current_path, paths, registry)

    # ── Triggers ──

    def extract_triggers(self, parsed: List[Dict]) -> List[str]:
        seen = set()
        triggers = []
        for clause in parsed:
            for t in clause.get("triggers", []):
                if t not in seen:
                    seen.add(t)
                    triggers.append(t)
        return triggers

    # ── Legacy compat ──

    def parse_cpg_text(self, text: str) -> List[Dict]:
        return self._parse_all(text)

    def build_decision_tree(self, parsed: List[Dict]):
        return self._build_tree(parsed)

    def extract_priority_paths(self, parsed: List[Dict]) -> List[PriorityPath]:
        paths = []
        for i, clause in enumerate(parsed):
            if clause.get("triggers") and clause.get("actions"):
                paths.append(PriorityPath(
                    node_ids=[f"n{i}"],
                    frequency=1,
                    description=f"{'; '.join(clause['triggers'][:2])} → {'; '.join(clause['actions'][:2])}",
                ))
        return paths
