// Minta Design Tokens — Tailwind maps semantic names to var(--minta-*).
// Single source of truth: web/src/design-system/tokens.css
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}', './index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary:         'var(--minta-primary)',
        'primary-dim':   'var(--minta-primary-dim)',
        'primary-hover': 'var(--minta-primary-hover)',
        'primary-subtle':'var(--minta-primary-subtle)',
        'on-primary':    'var(--minta-on-primary)',
        accent:          'var(--minta-primary-dim)',
        'accent-glow':   'var(--minta-accent-glow)',
        ink:             'var(--minta-ink)',
        'ink-secondary': 'var(--minta-ink-secondary)',
        'ink-muted':     'var(--minta-ink-muted)',
        cloud:           'var(--minta-cloud)',
        canvas:          'var(--minta-canvas)',
        'off-white':     'var(--minta-off-white)',
        surface:         'var(--minta-surface)',
        'surface-2':     'var(--minta-surface-2)',
        card:            'var(--minta-off-white)',
        border:          'var(--minta-border)',
        'border-subtle': 'var(--minta-border-subtle)',
        'border-strong': 'var(--minta-border-strong)',
        success:         'var(--minta-success)',
        warning:         'var(--minta-warning)',
        danger:          'var(--minta-danger)',
        'danger-hover':  'var(--minta-danger-hover)',
        'danger-subtle': 'var(--minta-danger-subtle)',
        'on-danger':     'var(--minta-on-danger)',
        info:            'var(--minta-info)',
        'authorize-border': 'var(--minta-authorize-border)',
        'tag-rose':      'var(--minta-tag-rose)',
        'tag-amber':     'var(--minta-tag-amber)',
        'tag-mint':      'var(--minta-tag-mint)',
        'tag-lavender':  'var(--minta-tag-lavender)',
      },
      fontFamily: {
        serif: ['Fraunces', 'Noto Serif SC', 'Georgia', 'serif'],
        sans:  ['system-ui', '-apple-system', 'Segoe UI', 'Noto Sans SC', 'Microsoft YaHei', 'sans-serif'],
        mono:  ['JetBrains Mono', 'Consolas', 'monospace'],
      },
      boxShadow: {
        sm:       'var(--minta-shadow-sm)',
        md:       'var(--minta-shadow-md)',
        lg:       'var(--minta-shadow-lg)',
        card:     'var(--minta-shadow-card)',
        hover:    'var(--minta-shadow-hover)',
        elevated: 'var(--minta-shadow-elevated)',
        glow:     'var(--minta-shadow-glow)',
      },
      borderRadius: {
        sm:   'var(--minta-radius-sm)',
        btn:  'var(--minta-radius-btn)',
        card: 'var(--minta-radius-card)',
      },
      transitionTimingFunction: {
        out: 'var(--minta-ease-out)',
      },
      transitionDuration: {
        fast:   'var(--minta-dur-fast)',
        normal: 'var(--minta-dur-normal)',
        slow:   'var(--minta-dur-slow)',
        reveal: 'var(--minta-dur-reveal)',
      },
    },
  },
  plugins: [],
};
